#!/bin/sh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
BRANCH_REGEX='^(feature|hotfix|release)\/[A-Z]+-[0-9]+(-[a-z0-9-]+)*$'

# Check if the branch name matches the defined regex
if ! [[ $BRANCH_NAME =~ $BRANCH_REGEX ]]; then
   echo "Branch name \"$BRANCH_NAME\" does not match the required naming convention."
   echo "Branch name must follow the pattern: (feature|hotfix|bugfix)/AB-123-description"	
   exit 1
else
   echo "Branch name \"$BRANCH_NAME\" follows the naming convention."
fi